#############################################################################
# Makefile for building: 
# Generated by qmake (3.0) (Qt 5.6.2)
# Project:  MAELab_CI.pro
# Template: app
# Command: /home/linhpc/miniconda2/bin/qmake -o Makefile MAELab_CI.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -fPIC -lpthread -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -fPIC -lpthread -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I/usr/local/include -I../../miniconda2/include/qt -I../../miniconda2/include/qt/QtOpenGL -I../../miniconda2/include/qt/QtWidgets -I../../miniconda2/include/qt/QtGui -I../../miniconda2/include/qt/QtCore -I. -I../../miniconda2/mkspecs/linux-g++
QMAKE         = /home/linhpc/miniconda2/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = 1.0.0
DISTDIR = /home/linhpc/Git/MAELab_2016/.tmp/1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/home/linhpc/miniconda2/lib
LIBS          = $(SUBLIBS) -L/usr/lib -L/home/linhpc/miniconda2/lib -lQt5OpenGL -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = io/JPEGReader.cpp \
		io/Reader.cpp \
		io/TPSReader.cpp \
		io/LibJpeg/jaricom.c \
		io/LibJpeg/jcapimin.c \
		io/LibJpeg/jcapistd.c \
		io/LibJpeg/jcarith.c \
		io/LibJpeg/jccoefct.c \
		io/LibJpeg/jccolor.c \
		io/LibJpeg/jcdctmgr.c \
		io/LibJpeg/jchuff.c \
		io/LibJpeg/jcinit.c \
		io/LibJpeg/jcmainct.c \
		io/LibJpeg/jcmarker.c \
		io/LibJpeg/jcmaster.c \
		io/LibJpeg/jcomapi.c \
		io/LibJpeg/jcparam.c \
		io/LibJpeg/jcprepct.c \
		io/LibJpeg/jcsample.c \
		io/LibJpeg/jctrans.c \
		io/LibJpeg/jdapimin.c \
		io/LibJpeg/jdapistd.c \
		io/LibJpeg/jdarith.c \
		io/LibJpeg/jdatadst.c \
		io/LibJpeg/jdatasrc.c \
		io/LibJpeg/jdcoefct.c \
		io/LibJpeg/jdcolor.c \
		io/LibJpeg/jddctmgr.c \
		io/LibJpeg/jdhuff.c \
		io/LibJpeg/jdinput.c \
		io/LibJpeg/jdmainct.c \
		io/LibJpeg/jdmarker.c \
		io/LibJpeg/jdmaster.c \
		io/LibJpeg/jdmerge.c \
		io/LibJpeg/jdpostct.c \
		io/LibJpeg/jdsample.c \
		io/LibJpeg/jdtrans.c \
		io/LibJpeg/jerror.c \
		io/LibJpeg/jfdctflt.c \
		io/LibJpeg/jfdctfst.c \
		io/LibJpeg/jfdctint.c \
		io/LibJpeg/jidctflt.c \
		io/LibJpeg/jidctfst.c \
		io/LibJpeg/jidctint.c \
		io/LibJpeg/jmemmgr.c \
		io/LibJpeg/jmemnobs.c \
		io/LibJpeg/jquant1.c \
		io/LibJpeg/jquant2.c \
		io/LibJpeg/jutils.c \
		imageModel/Edge.cpp \
		imageModel/Image.cpp \
		imageModel/Line.cpp \
		imageModel/Matrix.cpp \
		imageModel/Point.cpp \
		segmentation/Canny.cpp \
		segmentation/Filters.cpp \
		segmentation/Projection.cpp \
		segmentation/Suzuki.cpp \
		segmentation/Thresholds.cpp \
		histograms/LBP.cpp \
		histograms/ShapeHistogram.cpp \
		pht/GHTInPoint.cpp \
		pht/PCA.cpp \
		pht/PHoughTransform.cpp \
		pht/PHTEntry.cpp \
		pht/SVD.cpp \
		pointInterest/GeometricHistgoram.cpp \
		pointInterest/LandmarkDetection.cpp \
		pointInterest/ProHoughTransform.cpp \
		pointInterest/Segmentation.cpp \
		pointInterest/Treatments.cpp \
		correlation/CrossCorrelation.cpp \
		correlation/DescriptorDistance.cpp \
		utils/Converter.cpp \
		utils/Drawing.cpp \
		utils/ImageConvert.cpp \
		ui/ImageViewer.cpp \
		MAELab.cpp \
		MAELab_Test.cpp moc_ImageViewer.cpp
OBJECTS       = JPEGReader.o \
		Reader.o \
		TPSReader.o \
		jaricom.o \
		jcapimin.o \
		jcapistd.o \
		jcarith.o \
		jccoefct.o \
		jccolor.o \
		jcdctmgr.o \
		jchuff.o \
		jcinit.o \
		jcmainct.o \
		jcmarker.o \
		jcmaster.o \
		jcomapi.o \
		jcparam.o \
		jcprepct.o \
		jcsample.o \
		jctrans.o \
		jdapimin.o \
		jdapistd.o \
		jdarith.o \
		jdatadst.o \
		jdatasrc.o \
		jdcoefct.o \
		jdcolor.o \
		jddctmgr.o \
		jdhuff.o \
		jdinput.o \
		jdmainct.o \
		jdmarker.o \
		jdmaster.o \
		jdmerge.o \
		jdpostct.o \
		jdsample.o \
		jdtrans.o \
		jerror.o \
		jfdctflt.o \
		jfdctfst.o \
		jfdctint.o \
		jidctflt.o \
		jidctfst.o \
		jidctint.o \
		jmemmgr.o \
		jmemnobs.o \
		jquant1.o \
		jquant2.o \
		jutils.o \
		Edge.o \
		Image.o \
		Line.o \
		Matrix.o \
		Point.o \
		Canny.o \
		Filters.o \
		Projection.o \
		Suzuki.o \
		Thresholds.o \
		LBP.o \
		ShapeHistogram.o \
		GHTInPoint.o \
		PCA.o \
		PHoughTransform.o \
		PHTEntry.o \
		SVD.o \
		GeometricHistgoram.o \
		LandmarkDetection.o \
		ProHoughTransform.o \
		Segmentation.o \
		Treatments.o \
		CrossCorrelation.o \
		DescriptorDistance.o \
		Converter.o \
		Drawing.o \
		ImageConvert.o \
		ImageViewer.o \
		MAELab.o \
		MAELab_Test.o \
		moc_ImageViewer.o
DIST          = ../../miniconda2/mkspecs/features/spec_pre.prf \
		../../miniconda2/mkspecs/common/unix.conf \
		../../miniconda2/mkspecs/common/linux.conf \
		../../miniconda2/mkspecs/common/sanitize.conf \
		../../miniconda2/mkspecs/common/gcc-base.conf \
		../../miniconda2/mkspecs/common/gcc-base-unix.conf \
		../../miniconda2/mkspecs/common/g++-base.conf \
		../../miniconda2/mkspecs/common/g++-unix.conf \
		../../miniconda2/mkspecs/qconfig.pri \
		../../miniconda2/mkspecs/modules/qt_lib_bluetooth.pri \
		../../miniconda2/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../miniconda2/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../miniconda2/mkspecs/modules/qt_lib_clucene_private.pri \
		../../miniconda2/mkspecs/modules/qt_lib_concurrent.pri \
		../../miniconda2/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../miniconda2/mkspecs/modules/qt_lib_core.pri \
		../../miniconda2/mkspecs/modules/qt_lib_core_private.pri \
		../../miniconda2/mkspecs/modules/qt_lib_dbus.pri \
		../../miniconda2/mkspecs/modules/qt_lib_dbus_private.pri \
		../../miniconda2/mkspecs/modules/qt_lib_designer.pri \
		../../miniconda2/mkspecs/modules/qt_lib_designer_private.pri \
		../../miniconda2/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../miniconda2/mkspecs/modules/qt_lib_gui.pri \
		../../miniconda2/mkspecs/modules/qt_lib_gui_private.pri \
		../../miniconda2/mkspecs/modules/qt_lib_help.pri \
		../../miniconda2/mkspecs/modules/qt_lib_help_private.pri \
		../../miniconda2/mkspecs/modules/qt_lib_multimedia.pri \
		../../miniconda2/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../miniconda2/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../miniconda2/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../miniconda2/mkspecs/modules/qt_lib_network.pri \
		../../miniconda2/mkspecs/modules/qt_lib_network_private.pri \
		../../miniconda2/mkspecs/modules/qt_lib_nfc.pri \
		../../miniconda2/mkspecs/modules/qt_lib_nfc_private.pri \
		../../miniconda2/mkspecs/modules/qt_lib_opengl.pri \
		../../miniconda2/mkspecs/modules/qt_lib_opengl_private.pri \
		../../miniconda2/mkspecs/modules/qt_lib_openglextensions.pri \
		../../miniconda2/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../miniconda2/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../miniconda2/mkspecs/modules/qt_lib_printsupport.pri \
		../../miniconda2/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../miniconda2/mkspecs/modules/qt_lib_qml.pri \
		../../miniconda2/mkspecs/modules/qt_lib_qml_private.pri \
		../../miniconda2/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../miniconda2/mkspecs/modules/qt_lib_qmltest.pri \
		../../miniconda2/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../miniconda2/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../miniconda2/mkspecs/modules/qt_lib_quick.pri \
		../../miniconda2/mkspecs/modules/qt_lib_quick_private.pri \
		../../miniconda2/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../miniconda2/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../miniconda2/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../miniconda2/mkspecs/modules/qt_lib_script.pri \
		../../miniconda2/mkspecs/modules/qt_lib_script_private.pri \
		../../miniconda2/mkspecs/modules/qt_lib_scripttools.pri \
		../../miniconda2/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../miniconda2/mkspecs/modules/qt_lib_sql.pri \
		../../miniconda2/mkspecs/modules/qt_lib_sql_private.pri \
		../../miniconda2/mkspecs/modules/qt_lib_svg.pri \
		../../miniconda2/mkspecs/modules/qt_lib_svg_private.pri \
		../../miniconda2/mkspecs/modules/qt_lib_testlib.pri \
		../../miniconda2/mkspecs/modules/qt_lib_testlib_private.pri \
		../../miniconda2/mkspecs/modules/qt_lib_uiplugin.pri \
		../../miniconda2/mkspecs/modules/qt_lib_uitools.pri \
		../../miniconda2/mkspecs/modules/qt_lib_uitools_private.pri \
		../../miniconda2/mkspecs/modules/qt_lib_webchannel.pri \
		../../miniconda2/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../miniconda2/mkspecs/modules/qt_lib_webkit.pri \
		../../miniconda2/mkspecs/modules/qt_lib_webkit_private.pri \
		../../miniconda2/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../miniconda2/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../miniconda2/mkspecs/modules/qt_lib_websockets.pri \
		../../miniconda2/mkspecs/modules/qt_lib_websockets_private.pri \
		../../miniconda2/mkspecs/modules/qt_lib_widgets.pri \
		../../miniconda2/mkspecs/modules/qt_lib_widgets_private.pri \
		../../miniconda2/mkspecs/modules/qt_lib_x11extras.pri \
		../../miniconda2/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../miniconda2/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../miniconda2/mkspecs/modules/qt_lib_xml.pri \
		../../miniconda2/mkspecs/modules/qt_lib_xml_private.pri \
		../../miniconda2/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../miniconda2/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../miniconda2/mkspecs/features/qt_functions.prf \
		../../miniconda2/mkspecs/features/qt_config.prf \
		../../miniconda2/mkspecs/linux-g++/qmake.conf \
		../../miniconda2/mkspecs/features/spec_post.prf \
		../../miniconda2/mkspecs/features/exclusive_builds.prf \
		../../miniconda2/mkspecs/features/default_pre.prf \
		../../miniconda2/mkspecs/features/resolve_config.prf \
		../../miniconda2/mkspecs/features/default_post.prf \
		../../miniconda2/mkspecs/features/warn_on.prf \
		../../miniconda2/mkspecs/features/qt.prf \
		../../miniconda2/mkspecs/features/resources.prf \
		../../miniconda2/mkspecs/features/moc.prf \
		../../miniconda2/mkspecs/features/unix/opengl.prf \
		../../miniconda2/mkspecs/features/uic.prf \
		../../miniconda2/mkspecs/features/unix/thread.prf \
		../../miniconda2/mkspecs/features/file_copies.prf \
		../../miniconda2/mkspecs/features/testcase_targets.prf \
		../../miniconda2/mkspecs/features/exceptions.prf \
		../../miniconda2/mkspecs/features/yacc.prf \
		../../miniconda2/mkspecs/features/lex.prf \
		MAELab_CI.pro io/JPEGReader.h \
		io/Reader.h \
		io/TPSReader.h \
		io/LibJpeg/jconfig.h \
		io/LibJpeg/jdct.h \
		io/LibJpeg/jerror.h \
		io/LibJpeg/jinclude.h \
		io/LibJpeg/jmemsys.h \
		io/LibJpeg/jmorecfg.h \
		io/LibJpeg/jpegint.h \
		io/LibJpeg/jpeglib.h \
		io/LibJpeg/jversion.h \
		imageModel/Edge.h \
		imageModel/Image.h \
		imageModel/Line.h \
		imageModel/Matrix.h \
		imageModel/Point.h \
		segmentation/Canny.h \
		segmentation/Filters.h \
		segmentation/Projection.h \
		segmentation/Suzuki.h \
		segmentation/Thresholds.h \
		histograms/LBP.h \
		histograms/ShapeHistogram.h \
		pht/GHTInPoint.h \
		pht/PCA.h \
		pht/PHoughTransform.h \
		pht/PHTEntry.h \
		pht/SVD.h \
		pointInterest/GeometricHistgoram.h \
		pointInterest/LandmarkDetection.h \
		pointInterest/ProHoughTransform.h \
		pointInterest/Segmentation.h \
		pointInterest/Treatments.h \
		correlation/CrossCorrelation.h \
		correlation/DescriptorDistance.h \
		utils/Converter.h \
		utils/Drawing.h \
		utils/ImageConvert.h \
		ui/ImageViewer.h \
		MAELab.h io/JPEGReader.cpp \
		io/Reader.cpp \
		io/TPSReader.cpp \
		io/LibJpeg/jaricom.c \
		io/LibJpeg/jcapimin.c \
		io/LibJpeg/jcapistd.c \
		io/LibJpeg/jcarith.c \
		io/LibJpeg/jccoefct.c \
		io/LibJpeg/jccolor.c \
		io/LibJpeg/jcdctmgr.c \
		io/LibJpeg/jchuff.c \
		io/LibJpeg/jcinit.c \
		io/LibJpeg/jcmainct.c \
		io/LibJpeg/jcmarker.c \
		io/LibJpeg/jcmaster.c \
		io/LibJpeg/jcomapi.c \
		io/LibJpeg/jcparam.c \
		io/LibJpeg/jcprepct.c \
		io/LibJpeg/jcsample.c \
		io/LibJpeg/jctrans.c \
		io/LibJpeg/jdapimin.c \
		io/LibJpeg/jdapistd.c \
		io/LibJpeg/jdarith.c \
		io/LibJpeg/jdatadst.c \
		io/LibJpeg/jdatasrc.c \
		io/LibJpeg/jdcoefct.c \
		io/LibJpeg/jdcolor.c \
		io/LibJpeg/jddctmgr.c \
		io/LibJpeg/jdhuff.c \
		io/LibJpeg/jdinput.c \
		io/LibJpeg/jdmainct.c \
		io/LibJpeg/jdmarker.c \
		io/LibJpeg/jdmaster.c \
		io/LibJpeg/jdmerge.c \
		io/LibJpeg/jdpostct.c \
		io/LibJpeg/jdsample.c \
		io/LibJpeg/jdtrans.c \
		io/LibJpeg/jerror.c \
		io/LibJpeg/jfdctflt.c \
		io/LibJpeg/jfdctfst.c \
		io/LibJpeg/jfdctint.c \
		io/LibJpeg/jidctflt.c \
		io/LibJpeg/jidctfst.c \
		io/LibJpeg/jidctint.c \
		io/LibJpeg/jmemmgr.c \
		io/LibJpeg/jmemnobs.c \
		io/LibJpeg/jquant1.c \
		io/LibJpeg/jquant2.c \
		io/LibJpeg/jutils.c \
		imageModel/Edge.cpp \
		imageModel/Image.cpp \
		imageModel/Line.cpp \
		imageModel/Matrix.cpp \
		imageModel/Point.cpp \
		segmentation/Canny.cpp \
		segmentation/Filters.cpp \
		segmentation/Projection.cpp \
		segmentation/Suzuki.cpp \
		segmentation/Thresholds.cpp \
		histograms/LBP.cpp \
		histograms/ShapeHistogram.cpp \
		pht/GHTInPoint.cpp \
		pht/PCA.cpp \
		pht/PHoughTransform.cpp \
		pht/PHTEntry.cpp \
		pht/SVD.cpp \
		pointInterest/GeometricHistgoram.cpp \
		pointInterest/LandmarkDetection.cpp \
		pointInterest/ProHoughTransform.cpp \
		pointInterest/Segmentation.cpp \
		pointInterest/Treatments.cpp \
		correlation/CrossCorrelation.cpp \
		correlation/DescriptorDistance.cpp \
		utils/Converter.cpp \
		utils/Drawing.cpp \
		utils/ImageConvert.cpp \
		ui/ImageViewer.cpp \
		MAELab.cpp \
		MAELab_Test.cpp
QMAKE_TARGET  = 
DESTDIR       = 
TARGET        = 


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: MAELab_CI.pro ../../miniconda2/mkspecs/linux-g++/qmake.conf ../../miniconda2/mkspecs/features/spec_pre.prf \
		../../miniconda2/mkspecs/common/unix.conf \
		../../miniconda2/mkspecs/common/linux.conf \
		../../miniconda2/mkspecs/common/sanitize.conf \
		../../miniconda2/mkspecs/common/gcc-base.conf \
		../../miniconda2/mkspecs/common/gcc-base-unix.conf \
		../../miniconda2/mkspecs/common/g++-base.conf \
		../../miniconda2/mkspecs/common/g++-unix.conf \
		../../miniconda2/mkspecs/qconfig.pri \
		../../miniconda2/mkspecs/modules/qt_lib_bluetooth.pri \
		../../miniconda2/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../miniconda2/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../miniconda2/mkspecs/modules/qt_lib_clucene_private.pri \
		../../miniconda2/mkspecs/modules/qt_lib_concurrent.pri \
		../../miniconda2/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../miniconda2/mkspecs/modules/qt_lib_core.pri \
		../../miniconda2/mkspecs/modules/qt_lib_core_private.pri \
		../../miniconda2/mkspecs/modules/qt_lib_dbus.pri \
		../../miniconda2/mkspecs/modules/qt_lib_dbus_private.pri \
		../../miniconda2/mkspecs/modules/qt_lib_designer.pri \
		../../miniconda2/mkspecs/modules/qt_lib_designer_private.pri \
		../../miniconda2/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../miniconda2/mkspecs/modules/qt_lib_gui.pri \
		../../miniconda2/mkspecs/modules/qt_lib_gui_private.pri \
		../../miniconda2/mkspecs/modules/qt_lib_help.pri \
		../../miniconda2/mkspecs/modules/qt_lib_help_private.pri \
		../../miniconda2/mkspecs/modules/qt_lib_multimedia.pri \
		../../miniconda2/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../miniconda2/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../miniconda2/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../miniconda2/mkspecs/modules/qt_lib_network.pri \
		../../miniconda2/mkspecs/modules/qt_lib_network_private.pri \
		../../miniconda2/mkspecs/modules/qt_lib_nfc.pri \
		../../miniconda2/mkspecs/modules/qt_lib_nfc_private.pri \
		../../miniconda2/mkspecs/modules/qt_lib_opengl.pri \
		../../miniconda2/mkspecs/modules/qt_lib_opengl_private.pri \
		../../miniconda2/mkspecs/modules/qt_lib_openglextensions.pri \
		../../miniconda2/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../miniconda2/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../miniconda2/mkspecs/modules/qt_lib_printsupport.pri \
		../../miniconda2/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../miniconda2/mkspecs/modules/qt_lib_qml.pri \
		../../miniconda2/mkspecs/modules/qt_lib_qml_private.pri \
		../../miniconda2/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../miniconda2/mkspecs/modules/qt_lib_qmltest.pri \
		../../miniconda2/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../miniconda2/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../miniconda2/mkspecs/modules/qt_lib_quick.pri \
		../../miniconda2/mkspecs/modules/qt_lib_quick_private.pri \
		../../miniconda2/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../miniconda2/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../miniconda2/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../miniconda2/mkspecs/modules/qt_lib_script.pri \
		../../miniconda2/mkspecs/modules/qt_lib_script_private.pri \
		../../miniconda2/mkspecs/modules/qt_lib_scripttools.pri \
		../../miniconda2/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../miniconda2/mkspecs/modules/qt_lib_sql.pri \
		../../miniconda2/mkspecs/modules/qt_lib_sql_private.pri \
		../../miniconda2/mkspecs/modules/qt_lib_svg.pri \
		../../miniconda2/mkspecs/modules/qt_lib_svg_private.pri \
		../../miniconda2/mkspecs/modules/qt_lib_testlib.pri \
		../../miniconda2/mkspecs/modules/qt_lib_testlib_private.pri \
		../../miniconda2/mkspecs/modules/qt_lib_uiplugin.pri \
		../../miniconda2/mkspecs/modules/qt_lib_uitools.pri \
		../../miniconda2/mkspecs/modules/qt_lib_uitools_private.pri \
		../../miniconda2/mkspecs/modules/qt_lib_webchannel.pri \
		../../miniconda2/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../miniconda2/mkspecs/modules/qt_lib_webkit.pri \
		../../miniconda2/mkspecs/modules/qt_lib_webkit_private.pri \
		../../miniconda2/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../miniconda2/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../miniconda2/mkspecs/modules/qt_lib_websockets.pri \
		../../miniconda2/mkspecs/modules/qt_lib_websockets_private.pri \
		../../miniconda2/mkspecs/modules/qt_lib_widgets.pri \
		../../miniconda2/mkspecs/modules/qt_lib_widgets_private.pri \
		../../miniconda2/mkspecs/modules/qt_lib_x11extras.pri \
		../../miniconda2/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../miniconda2/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../miniconda2/mkspecs/modules/qt_lib_xml.pri \
		../../miniconda2/mkspecs/modules/qt_lib_xml_private.pri \
		../../miniconda2/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../miniconda2/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../miniconda2/mkspecs/features/qt_functions.prf \
		../../miniconda2/mkspecs/features/qt_config.prf \
		../../miniconda2/mkspecs/linux-g++/qmake.conf \
		../../miniconda2/mkspecs/features/spec_post.prf \
		../../miniconda2/mkspecs/features/exclusive_builds.prf \
		../../miniconda2/mkspecs/features/default_pre.prf \
		../../miniconda2/mkspecs/features/resolve_config.prf \
		../../miniconda2/mkspecs/features/default_post.prf \
		../../miniconda2/mkspecs/features/warn_on.prf \
		../../miniconda2/mkspecs/features/qt.prf \
		../../miniconda2/mkspecs/features/resources.prf \
		../../miniconda2/mkspecs/features/moc.prf \
		../../miniconda2/mkspecs/features/unix/opengl.prf \
		../../miniconda2/mkspecs/features/uic.prf \
		../../miniconda2/mkspecs/features/unix/thread.prf \
		../../miniconda2/mkspecs/features/file_copies.prf \
		../../miniconda2/mkspecs/features/testcase_targets.prf \
		../../miniconda2/mkspecs/features/exceptions.prf \
		../../miniconda2/mkspecs/features/yacc.prf \
		../../miniconda2/mkspecs/features/lex.prf \
		MAELab_CI.pro \
		../../miniconda2/lib/libQt5OpenGL.prl \
		../../miniconda2/lib/libQt5Widgets.prl \
		../../miniconda2/lib/libQt5Gui.prl \
		../../miniconda2/lib/libQt5Core.prl
	$(QMAKE) -o Makefile MAELab_CI.pro
../../miniconda2/mkspecs/features/spec_pre.prf:
../../miniconda2/mkspecs/common/unix.conf:
../../miniconda2/mkspecs/common/linux.conf:
../../miniconda2/mkspecs/common/sanitize.conf:
../../miniconda2/mkspecs/common/gcc-base.conf:
../../miniconda2/mkspecs/common/gcc-base-unix.conf:
../../miniconda2/mkspecs/common/g++-base.conf:
../../miniconda2/mkspecs/common/g++-unix.conf:
../../miniconda2/mkspecs/qconfig.pri:
../../miniconda2/mkspecs/modules/qt_lib_bluetooth.pri:
../../miniconda2/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../miniconda2/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../miniconda2/mkspecs/modules/qt_lib_clucene_private.pri:
../../miniconda2/mkspecs/modules/qt_lib_concurrent.pri:
../../miniconda2/mkspecs/modules/qt_lib_concurrent_private.pri:
../../miniconda2/mkspecs/modules/qt_lib_core.pri:
../../miniconda2/mkspecs/modules/qt_lib_core_private.pri:
../../miniconda2/mkspecs/modules/qt_lib_dbus.pri:
../../miniconda2/mkspecs/modules/qt_lib_dbus_private.pri:
../../miniconda2/mkspecs/modules/qt_lib_designer.pri:
../../miniconda2/mkspecs/modules/qt_lib_designer_private.pri:
../../miniconda2/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../miniconda2/mkspecs/modules/qt_lib_gui.pri:
../../miniconda2/mkspecs/modules/qt_lib_gui_private.pri:
../../miniconda2/mkspecs/modules/qt_lib_help.pri:
../../miniconda2/mkspecs/modules/qt_lib_help_private.pri:
../../miniconda2/mkspecs/modules/qt_lib_multimedia.pri:
../../miniconda2/mkspecs/modules/qt_lib_multimedia_private.pri:
../../miniconda2/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../miniconda2/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../miniconda2/mkspecs/modules/qt_lib_network.pri:
../../miniconda2/mkspecs/modules/qt_lib_network_private.pri:
../../miniconda2/mkspecs/modules/qt_lib_nfc.pri:
../../miniconda2/mkspecs/modules/qt_lib_nfc_private.pri:
../../miniconda2/mkspecs/modules/qt_lib_opengl.pri:
../../miniconda2/mkspecs/modules/qt_lib_opengl_private.pri:
../../miniconda2/mkspecs/modules/qt_lib_openglextensions.pri:
../../miniconda2/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../miniconda2/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../miniconda2/mkspecs/modules/qt_lib_printsupport.pri:
../../miniconda2/mkspecs/modules/qt_lib_printsupport_private.pri:
../../miniconda2/mkspecs/modules/qt_lib_qml.pri:
../../miniconda2/mkspecs/modules/qt_lib_qml_private.pri:
../../miniconda2/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../miniconda2/mkspecs/modules/qt_lib_qmltest.pri:
../../miniconda2/mkspecs/modules/qt_lib_qmltest_private.pri:
../../miniconda2/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../miniconda2/mkspecs/modules/qt_lib_quick.pri:
../../miniconda2/mkspecs/modules/qt_lib_quick_private.pri:
../../miniconda2/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../miniconda2/mkspecs/modules/qt_lib_quickwidgets.pri:
../../miniconda2/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../miniconda2/mkspecs/modules/qt_lib_script.pri:
../../miniconda2/mkspecs/modules/qt_lib_script_private.pri:
../../miniconda2/mkspecs/modules/qt_lib_scripttools.pri:
../../miniconda2/mkspecs/modules/qt_lib_scripttools_private.pri:
../../miniconda2/mkspecs/modules/qt_lib_sql.pri:
../../miniconda2/mkspecs/modules/qt_lib_sql_private.pri:
../../miniconda2/mkspecs/modules/qt_lib_svg.pri:
../../miniconda2/mkspecs/modules/qt_lib_svg_private.pri:
../../miniconda2/mkspecs/modules/qt_lib_testlib.pri:
../../miniconda2/mkspecs/modules/qt_lib_testlib_private.pri:
../../miniconda2/mkspecs/modules/qt_lib_uiplugin.pri:
../../miniconda2/mkspecs/modules/qt_lib_uitools.pri:
../../miniconda2/mkspecs/modules/qt_lib_uitools_private.pri:
../../miniconda2/mkspecs/modules/qt_lib_webchannel.pri:
../../miniconda2/mkspecs/modules/qt_lib_webchannel_private.pri:
../../miniconda2/mkspecs/modules/qt_lib_webkit.pri:
../../miniconda2/mkspecs/modules/qt_lib_webkit_private.pri:
../../miniconda2/mkspecs/modules/qt_lib_webkitwidgets.pri:
../../miniconda2/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
../../miniconda2/mkspecs/modules/qt_lib_websockets.pri:
../../miniconda2/mkspecs/modules/qt_lib_websockets_private.pri:
../../miniconda2/mkspecs/modules/qt_lib_widgets.pri:
../../miniconda2/mkspecs/modules/qt_lib_widgets_private.pri:
../../miniconda2/mkspecs/modules/qt_lib_x11extras.pri:
../../miniconda2/mkspecs/modules/qt_lib_x11extras_private.pri:
../../miniconda2/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
../../miniconda2/mkspecs/modules/qt_lib_xml.pri:
../../miniconda2/mkspecs/modules/qt_lib_xml_private.pri:
../../miniconda2/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../miniconda2/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../miniconda2/mkspecs/features/qt_functions.prf:
../../miniconda2/mkspecs/features/qt_config.prf:
../../miniconda2/mkspecs/linux-g++/qmake.conf:
../../miniconda2/mkspecs/features/spec_post.prf:
../../miniconda2/mkspecs/features/exclusive_builds.prf:
../../miniconda2/mkspecs/features/default_pre.prf:
../../miniconda2/mkspecs/features/resolve_config.prf:
../../miniconda2/mkspecs/features/default_post.prf:
../../miniconda2/mkspecs/features/warn_on.prf:
../../miniconda2/mkspecs/features/qt.prf:
../../miniconda2/mkspecs/features/resources.prf:
../../miniconda2/mkspecs/features/moc.prf:
../../miniconda2/mkspecs/features/unix/opengl.prf:
../../miniconda2/mkspecs/features/uic.prf:
../../miniconda2/mkspecs/features/unix/thread.prf:
../../miniconda2/mkspecs/features/file_copies.prf:
../../miniconda2/mkspecs/features/testcase_targets.prf:
../../miniconda2/mkspecs/features/exceptions.prf:
../../miniconda2/mkspecs/features/yacc.prf:
../../miniconda2/mkspecs/features/lex.prf:
MAELab_CI.pro:
../../miniconda2/lib/libQt5OpenGL.prl:
../../miniconda2/lib/libQt5Widgets.prl:
../../miniconda2/lib/libQt5Gui.prl:
../../miniconda2/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile MAELab_CI.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents io/JPEGReader.h io/Reader.h io/TPSReader.h io/LibJpeg/jconfig.h io/LibJpeg/jdct.h io/LibJpeg/jerror.h io/LibJpeg/jinclude.h io/LibJpeg/jmemsys.h io/LibJpeg/jmorecfg.h io/LibJpeg/jpegint.h io/LibJpeg/jpeglib.h io/LibJpeg/jversion.h imageModel/Edge.h imageModel/Image.h imageModel/Line.h imageModel/Matrix.h imageModel/Point.h segmentation/Canny.h segmentation/Filters.h segmentation/Projection.h segmentation/Suzuki.h segmentation/Thresholds.h histograms/LBP.h histograms/ShapeHistogram.h pht/GHTInPoint.h pht/PCA.h pht/PHoughTransform.h pht/PHTEntry.h pht/SVD.h pointInterest/GeometricHistgoram.h pointInterest/LandmarkDetection.h pointInterest/ProHoughTransform.h pointInterest/Segmentation.h pointInterest/Treatments.h correlation/CrossCorrelation.h correlation/DescriptorDistance.h utils/Converter.h utils/Drawing.h utils/ImageConvert.h ui/ImageViewer.h MAELab.h $(DISTDIR)/
	$(COPY_FILE) --parents io/JPEGReader.cpp io/Reader.cpp io/TPSReader.cpp io/LibJpeg/jaricom.c io/LibJpeg/jcapimin.c io/LibJpeg/jcapistd.c io/LibJpeg/jcarith.c io/LibJpeg/jccoefct.c io/LibJpeg/jccolor.c io/LibJpeg/jcdctmgr.c io/LibJpeg/jchuff.c io/LibJpeg/jcinit.c io/LibJpeg/jcmainct.c io/LibJpeg/jcmarker.c io/LibJpeg/jcmaster.c io/LibJpeg/jcomapi.c io/LibJpeg/jcparam.c io/LibJpeg/jcprepct.c io/LibJpeg/jcsample.c io/LibJpeg/jctrans.c io/LibJpeg/jdapimin.c io/LibJpeg/jdapistd.c io/LibJpeg/jdarith.c io/LibJpeg/jdatadst.c io/LibJpeg/jdatasrc.c io/LibJpeg/jdcoefct.c io/LibJpeg/jdcolor.c io/LibJpeg/jddctmgr.c io/LibJpeg/jdhuff.c io/LibJpeg/jdinput.c io/LibJpeg/jdmainct.c io/LibJpeg/jdmarker.c io/LibJpeg/jdmaster.c io/LibJpeg/jdmerge.c io/LibJpeg/jdpostct.c io/LibJpeg/jdsample.c io/LibJpeg/jdtrans.c io/LibJpeg/jerror.c io/LibJpeg/jfdctflt.c io/LibJpeg/jfdctfst.c io/LibJpeg/jfdctint.c io/LibJpeg/jidctflt.c io/LibJpeg/jidctfst.c io/LibJpeg/jidctint.c io/LibJpeg/jmemmgr.c io/LibJpeg/jmemnobs.c io/LibJpeg/jquant1.c io/LibJpeg/jquant2.c io/LibJpeg/jutils.c imageModel/Edge.cpp imageModel/Image.cpp imageModel/Line.cpp imageModel/Matrix.cpp imageModel/Point.cpp segmentation/Canny.cpp segmentation/Filters.cpp segmentation/Projection.cpp segmentation/Suzuki.cpp segmentation/Thresholds.cpp histograms/LBP.cpp histograms/ShapeHistogram.cpp pht/GHTInPoint.cpp pht/PCA.cpp pht/PHoughTransform.cpp pht/PHTEntry.cpp pht/SVD.cpp pointInterest/GeometricHistgoram.cpp pointInterest/LandmarkDetection.cpp pointInterest/ProHoughTransform.cpp pointInterest/Segmentation.cpp pointInterest/Treatments.cpp correlation/CrossCorrelation.cpp correlation/DescriptorDistance.cpp utils/Converter.cpp utils/Drawing.cpp utils/ImageConvert.cpp ui/ImageViewer.cpp MAELab.cpp MAELab_Test.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_ImageViewer.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_ImageViewer.cpp
moc_ImageViewer.cpp: imageModel/Point.h \
		ui/ImageViewer.h
	/home/linhpc/miniconda2/bin/moc $(DEFINES) -I/home/linhpc/miniconda2/mkspecs/linux-g++ -I/home/linhpc/Git/MAELab_2016 -I/usr/local/include -I/home/linhpc/miniconda2/include/qt -I/home/linhpc/miniconda2/include/qt/QtOpenGL -I/home/linhpc/miniconda2/include/qt/QtWidgets -I/home/linhpc/miniconda2/include/qt/QtGui -I/home/linhpc/miniconda2/include/qt/QtCore -I/home/linhpc/miniconda2/x86_64-conda_cos6-linux-gnu/include/c++/7.2.0 -I/home/linhpc/miniconda2/x86_64-conda_cos6-linux-gnu/include/c++/7.2.0/x86_64-conda_cos6-linux-gnu -I/home/linhpc/miniconda2/x86_64-conda_cos6-linux-gnu/include/c++/7.2.0/backward -I/home/linhpc/miniconda2/lib/gcc/x86_64-conda_cos6-linux-gnu/7.2.0/include -I/home/linhpc/miniconda2/lib/gcc/x86_64-conda_cos6-linux-gnu/7.2.0/include-fixed -I/home/linhpc/miniconda2/x86_64-conda_cos6-linux-gnu/include -I/home/linhpc/miniconda2/x86_64-conda_cos6-linux-gnu/sysroot/usr/include ui/ImageViewer.h -o moc_ImageViewer.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

JPEGReader.o: io/JPEGReader.cpp io/LibJpeg/jpeglib.h \
		io/LibJpeg/jconfig.h \
		io/LibJpeg/jmorecfg.h \
		io/LibJpeg/jpegint.h \
		io/LibJpeg/jerror.h \
		imageModel/Point.h \
		imageModel/Matrix.h \
		io/JPEGReader.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o JPEGReader.o io/JPEGReader.cpp

Reader.o: io/Reader.cpp imageModel/Point.h \
		imageModel/Matrix.h \
		io/TPSReader.h \
		io/JPEGReader.h \
		io/Reader.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Reader.o io/Reader.cpp

TPSReader.o: io/TPSReader.cpp imageModel/Point.h \
		io/TPSReader.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TPSReader.o io/TPSReader.cpp

jaricom.o: io/LibJpeg/jaricom.c io/LibJpeg/jinclude.h \
		io/LibJpeg/jconfig.h \
		io/LibJpeg/jpeglib.h \
		io/LibJpeg/jmorecfg.h \
		io/LibJpeg/jpegint.h \
		io/LibJpeg/jerror.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o jaricom.o io/LibJpeg/jaricom.c

jcapimin.o: io/LibJpeg/jcapimin.c io/LibJpeg/jinclude.h \
		io/LibJpeg/jconfig.h \
		io/LibJpeg/jpeglib.h \
		io/LibJpeg/jmorecfg.h \
		io/LibJpeg/jpegint.h \
		io/LibJpeg/jerror.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o jcapimin.o io/LibJpeg/jcapimin.c

jcapistd.o: io/LibJpeg/jcapistd.c io/LibJpeg/jinclude.h \
		io/LibJpeg/jconfig.h \
		io/LibJpeg/jpeglib.h \
		io/LibJpeg/jmorecfg.h \
		io/LibJpeg/jpegint.h \
		io/LibJpeg/jerror.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o jcapistd.o io/LibJpeg/jcapistd.c

jcarith.o: io/LibJpeg/jcarith.c io/LibJpeg/jinclude.h \
		io/LibJpeg/jconfig.h \
		io/LibJpeg/jpeglib.h \
		io/LibJpeg/jmorecfg.h \
		io/LibJpeg/jpegint.h \
		io/LibJpeg/jerror.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o jcarith.o io/LibJpeg/jcarith.c

jccoefct.o: io/LibJpeg/jccoefct.c io/LibJpeg/jinclude.h \
		io/LibJpeg/jconfig.h \
		io/LibJpeg/jpeglib.h \
		io/LibJpeg/jmorecfg.h \
		io/LibJpeg/jpegint.h \
		io/LibJpeg/jerror.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o jccoefct.o io/LibJpeg/jccoefct.c

jccolor.o: io/LibJpeg/jccolor.c io/LibJpeg/jinclude.h \
		io/LibJpeg/jconfig.h \
		io/LibJpeg/jpeglib.h \
		io/LibJpeg/jmorecfg.h \
		io/LibJpeg/jpegint.h \
		io/LibJpeg/jerror.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o jccolor.o io/LibJpeg/jccolor.c

jcdctmgr.o: io/LibJpeg/jcdctmgr.c io/LibJpeg/jinclude.h \
		io/LibJpeg/jconfig.h \
		io/LibJpeg/jpeglib.h \
		io/LibJpeg/jmorecfg.h \
		io/LibJpeg/jpegint.h \
		io/LibJpeg/jerror.h \
		io/LibJpeg/jdct.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o jcdctmgr.o io/LibJpeg/jcdctmgr.c

jchuff.o: io/LibJpeg/jchuff.c io/LibJpeg/jinclude.h \
		io/LibJpeg/jconfig.h \
		io/LibJpeg/jpeglib.h \
		io/LibJpeg/jmorecfg.h \
		io/LibJpeg/jpegint.h \
		io/LibJpeg/jerror.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o jchuff.o io/LibJpeg/jchuff.c

jcinit.o: io/LibJpeg/jcinit.c io/LibJpeg/jinclude.h \
		io/LibJpeg/jconfig.h \
		io/LibJpeg/jpeglib.h \
		io/LibJpeg/jmorecfg.h \
		io/LibJpeg/jpegint.h \
		io/LibJpeg/jerror.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o jcinit.o io/LibJpeg/jcinit.c

jcmainct.o: io/LibJpeg/jcmainct.c io/LibJpeg/jinclude.h \
		io/LibJpeg/jconfig.h \
		io/LibJpeg/jpeglib.h \
		io/LibJpeg/jmorecfg.h \
		io/LibJpeg/jpegint.h \
		io/LibJpeg/jerror.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o jcmainct.o io/LibJpeg/jcmainct.c

jcmarker.o: io/LibJpeg/jcmarker.c io/LibJpeg/jinclude.h \
		io/LibJpeg/jconfig.h \
		io/LibJpeg/jpeglib.h \
		io/LibJpeg/jmorecfg.h \
		io/LibJpeg/jpegint.h \
		io/LibJpeg/jerror.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o jcmarker.o io/LibJpeg/jcmarker.c

jcmaster.o: io/LibJpeg/jcmaster.c io/LibJpeg/jinclude.h \
		io/LibJpeg/jconfig.h \
		io/LibJpeg/jpeglib.h \
		io/LibJpeg/jmorecfg.h \
		io/LibJpeg/jpegint.h \
		io/LibJpeg/jerror.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o jcmaster.o io/LibJpeg/jcmaster.c

jcomapi.o: io/LibJpeg/jcomapi.c io/LibJpeg/jinclude.h \
		io/LibJpeg/jconfig.h \
		io/LibJpeg/jpeglib.h \
		io/LibJpeg/jmorecfg.h \
		io/LibJpeg/jpegint.h \
		io/LibJpeg/jerror.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o jcomapi.o io/LibJpeg/jcomapi.c

jcparam.o: io/LibJpeg/jcparam.c io/LibJpeg/jinclude.h \
		io/LibJpeg/jconfig.h \
		io/LibJpeg/jpeglib.h \
		io/LibJpeg/jmorecfg.h \
		io/LibJpeg/jpegint.h \
		io/LibJpeg/jerror.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o jcparam.o io/LibJpeg/jcparam.c

jcprepct.o: io/LibJpeg/jcprepct.c io/LibJpeg/jinclude.h \
		io/LibJpeg/jconfig.h \
		io/LibJpeg/jpeglib.h \
		io/LibJpeg/jmorecfg.h \
		io/LibJpeg/jpegint.h \
		io/LibJpeg/jerror.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o jcprepct.o io/LibJpeg/jcprepct.c

jcsample.o: io/LibJpeg/jcsample.c io/LibJpeg/jinclude.h \
		io/LibJpeg/jconfig.h \
		io/LibJpeg/jpeglib.h \
		io/LibJpeg/jmorecfg.h \
		io/LibJpeg/jpegint.h \
		io/LibJpeg/jerror.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o jcsample.o io/LibJpeg/jcsample.c

jctrans.o: io/LibJpeg/jctrans.c io/LibJpeg/jinclude.h \
		io/LibJpeg/jconfig.h \
		io/LibJpeg/jpeglib.h \
		io/LibJpeg/jmorecfg.h \
		io/LibJpeg/jpegint.h \
		io/LibJpeg/jerror.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o jctrans.o io/LibJpeg/jctrans.c

jdapimin.o: io/LibJpeg/jdapimin.c io/LibJpeg/jinclude.h \
		io/LibJpeg/jconfig.h \
		io/LibJpeg/jpeglib.h \
		io/LibJpeg/jmorecfg.h \
		io/LibJpeg/jpegint.h \
		io/LibJpeg/jerror.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o jdapimin.o io/LibJpeg/jdapimin.c

jdapistd.o: io/LibJpeg/jdapistd.c io/LibJpeg/jinclude.h \
		io/LibJpeg/jconfig.h \
		io/LibJpeg/jpeglib.h \
		io/LibJpeg/jmorecfg.h \
		io/LibJpeg/jpegint.h \
		io/LibJpeg/jerror.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o jdapistd.o io/LibJpeg/jdapistd.c

jdarith.o: io/LibJpeg/jdarith.c io/LibJpeg/jinclude.h \
		io/LibJpeg/jconfig.h \
		io/LibJpeg/jpeglib.h \
		io/LibJpeg/jmorecfg.h \
		io/LibJpeg/jpegint.h \
		io/LibJpeg/jerror.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o jdarith.o io/LibJpeg/jdarith.c

jdatadst.o: io/LibJpeg/jdatadst.c io/LibJpeg/jinclude.h \
		io/LibJpeg/jconfig.h \
		io/LibJpeg/jpeglib.h \
		io/LibJpeg/jmorecfg.h \
		io/LibJpeg/jpegint.h \
		io/LibJpeg/jerror.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o jdatadst.o io/LibJpeg/jdatadst.c

jdatasrc.o: io/LibJpeg/jdatasrc.c io/LibJpeg/jinclude.h \
		io/LibJpeg/jconfig.h \
		io/LibJpeg/jpeglib.h \
		io/LibJpeg/jmorecfg.h \
		io/LibJpeg/jpegint.h \
		io/LibJpeg/jerror.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o jdatasrc.o io/LibJpeg/jdatasrc.c

jdcoefct.o: io/LibJpeg/jdcoefct.c io/LibJpeg/jinclude.h \
		io/LibJpeg/jconfig.h \
		io/LibJpeg/jpeglib.h \
		io/LibJpeg/jmorecfg.h \
		io/LibJpeg/jpegint.h \
		io/LibJpeg/jerror.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o jdcoefct.o io/LibJpeg/jdcoefct.c

jdcolor.o: io/LibJpeg/jdcolor.c io/LibJpeg/jinclude.h \
		io/LibJpeg/jconfig.h \
		io/LibJpeg/jpeglib.h \
		io/LibJpeg/jmorecfg.h \
		io/LibJpeg/jpegint.h \
		io/LibJpeg/jerror.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o jdcolor.o io/LibJpeg/jdcolor.c

jddctmgr.o: io/LibJpeg/jddctmgr.c io/LibJpeg/jinclude.h \
		io/LibJpeg/jconfig.h \
		io/LibJpeg/jpeglib.h \
		io/LibJpeg/jmorecfg.h \
		io/LibJpeg/jpegint.h \
		io/LibJpeg/jerror.h \
		io/LibJpeg/jdct.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o jddctmgr.o io/LibJpeg/jddctmgr.c

jdhuff.o: io/LibJpeg/jdhuff.c io/LibJpeg/jinclude.h \
		io/LibJpeg/jconfig.h \
		io/LibJpeg/jpeglib.h \
		io/LibJpeg/jmorecfg.h \
		io/LibJpeg/jpegint.h \
		io/LibJpeg/jerror.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o jdhuff.o io/LibJpeg/jdhuff.c

jdinput.o: io/LibJpeg/jdinput.c io/LibJpeg/jinclude.h \
		io/LibJpeg/jconfig.h \
		io/LibJpeg/jpeglib.h \
		io/LibJpeg/jmorecfg.h \
		io/LibJpeg/jpegint.h \
		io/LibJpeg/jerror.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o jdinput.o io/LibJpeg/jdinput.c

jdmainct.o: io/LibJpeg/jdmainct.c io/LibJpeg/jinclude.h \
		io/LibJpeg/jconfig.h \
		io/LibJpeg/jpeglib.h \
		io/LibJpeg/jmorecfg.h \
		io/LibJpeg/jpegint.h \
		io/LibJpeg/jerror.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o jdmainct.o io/LibJpeg/jdmainct.c

jdmarker.o: io/LibJpeg/jdmarker.c io/LibJpeg/jinclude.h \
		io/LibJpeg/jconfig.h \
		io/LibJpeg/jpeglib.h \
		io/LibJpeg/jmorecfg.h \
		io/LibJpeg/jpegint.h \
		io/LibJpeg/jerror.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o jdmarker.o io/LibJpeg/jdmarker.c

jdmaster.o: io/LibJpeg/jdmaster.c io/LibJpeg/jinclude.h \
		io/LibJpeg/jconfig.h \
		io/LibJpeg/jpeglib.h \
		io/LibJpeg/jmorecfg.h \
		io/LibJpeg/jpegint.h \
		io/LibJpeg/jerror.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o jdmaster.o io/LibJpeg/jdmaster.c

jdmerge.o: io/LibJpeg/jdmerge.c io/LibJpeg/jinclude.h \
		io/LibJpeg/jconfig.h \
		io/LibJpeg/jpeglib.h \
		io/LibJpeg/jmorecfg.h \
		io/LibJpeg/jpegint.h \
		io/LibJpeg/jerror.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o jdmerge.o io/LibJpeg/jdmerge.c

jdpostct.o: io/LibJpeg/jdpostct.c io/LibJpeg/jinclude.h \
		io/LibJpeg/jconfig.h \
		io/LibJpeg/jpeglib.h \
		io/LibJpeg/jmorecfg.h \
		io/LibJpeg/jpegint.h \
		io/LibJpeg/jerror.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o jdpostct.o io/LibJpeg/jdpostct.c

jdsample.o: io/LibJpeg/jdsample.c io/LibJpeg/jinclude.h \
		io/LibJpeg/jconfig.h \
		io/LibJpeg/jpeglib.h \
		io/LibJpeg/jmorecfg.h \
		io/LibJpeg/jpegint.h \
		io/LibJpeg/jerror.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o jdsample.o io/LibJpeg/jdsample.c

jdtrans.o: io/LibJpeg/jdtrans.c io/LibJpeg/jinclude.h \
		io/LibJpeg/jconfig.h \
		io/LibJpeg/jpeglib.h \
		io/LibJpeg/jmorecfg.h \
		io/LibJpeg/jpegint.h \
		io/LibJpeg/jerror.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o jdtrans.o io/LibJpeg/jdtrans.c

jerror.o: io/LibJpeg/jerror.c io/LibJpeg/jinclude.h \
		io/LibJpeg/jconfig.h \
		io/LibJpeg/jpeglib.h \
		io/LibJpeg/jmorecfg.h \
		io/LibJpeg/jpegint.h \
		io/LibJpeg/jerror.h \
		io/LibJpeg/jversion.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o jerror.o io/LibJpeg/jerror.c

jfdctflt.o: io/LibJpeg/jfdctflt.c io/LibJpeg/jinclude.h \
		io/LibJpeg/jconfig.h \
		io/LibJpeg/jpeglib.h \
		io/LibJpeg/jmorecfg.h \
		io/LibJpeg/jpegint.h \
		io/LibJpeg/jerror.h \
		io/LibJpeg/jdct.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o jfdctflt.o io/LibJpeg/jfdctflt.c

jfdctfst.o: io/LibJpeg/jfdctfst.c io/LibJpeg/jinclude.h \
		io/LibJpeg/jconfig.h \
		io/LibJpeg/jpeglib.h \
		io/LibJpeg/jmorecfg.h \
		io/LibJpeg/jpegint.h \
		io/LibJpeg/jerror.h \
		io/LibJpeg/jdct.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o jfdctfst.o io/LibJpeg/jfdctfst.c

jfdctint.o: io/LibJpeg/jfdctint.c io/LibJpeg/jinclude.h \
		io/LibJpeg/jconfig.h \
		io/LibJpeg/jpeglib.h \
		io/LibJpeg/jmorecfg.h \
		io/LibJpeg/jpegint.h \
		io/LibJpeg/jerror.h \
		io/LibJpeg/jdct.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o jfdctint.o io/LibJpeg/jfdctint.c

jidctflt.o: io/LibJpeg/jidctflt.c io/LibJpeg/jinclude.h \
		io/LibJpeg/jconfig.h \
		io/LibJpeg/jpeglib.h \
		io/LibJpeg/jmorecfg.h \
		io/LibJpeg/jpegint.h \
		io/LibJpeg/jerror.h \
		io/LibJpeg/jdct.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o jidctflt.o io/LibJpeg/jidctflt.c

jidctfst.o: io/LibJpeg/jidctfst.c io/LibJpeg/jinclude.h \
		io/LibJpeg/jconfig.h \
		io/LibJpeg/jpeglib.h \
		io/LibJpeg/jmorecfg.h \
		io/LibJpeg/jpegint.h \
		io/LibJpeg/jerror.h \
		io/LibJpeg/jdct.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o jidctfst.o io/LibJpeg/jidctfst.c

jidctint.o: io/LibJpeg/jidctint.c io/LibJpeg/jinclude.h \
		io/LibJpeg/jconfig.h \
		io/LibJpeg/jpeglib.h \
		io/LibJpeg/jmorecfg.h \
		io/LibJpeg/jpegint.h \
		io/LibJpeg/jerror.h \
		io/LibJpeg/jdct.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o jidctint.o io/LibJpeg/jidctint.c

jmemmgr.o: io/LibJpeg/jmemmgr.c io/LibJpeg/jinclude.h \
		io/LibJpeg/jconfig.h \
		io/LibJpeg/jpeglib.h \
		io/LibJpeg/jmorecfg.h \
		io/LibJpeg/jpegint.h \
		io/LibJpeg/jerror.h \
		io/LibJpeg/jmemsys.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o jmemmgr.o io/LibJpeg/jmemmgr.c

jmemnobs.o: io/LibJpeg/jmemnobs.c io/LibJpeg/jinclude.h \
		io/LibJpeg/jconfig.h \
		io/LibJpeg/jpeglib.h \
		io/LibJpeg/jmorecfg.h \
		io/LibJpeg/jpegint.h \
		io/LibJpeg/jerror.h \
		io/LibJpeg/jmemsys.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o jmemnobs.o io/LibJpeg/jmemnobs.c

jquant1.o: io/LibJpeg/jquant1.c io/LibJpeg/jinclude.h \
		io/LibJpeg/jconfig.h \
		io/LibJpeg/jpeglib.h \
		io/LibJpeg/jmorecfg.h \
		io/LibJpeg/jpegint.h \
		io/LibJpeg/jerror.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o jquant1.o io/LibJpeg/jquant1.c

jquant2.o: io/LibJpeg/jquant2.c io/LibJpeg/jinclude.h \
		io/LibJpeg/jconfig.h \
		io/LibJpeg/jpeglib.h \
		io/LibJpeg/jmorecfg.h \
		io/LibJpeg/jpegint.h \
		io/LibJpeg/jerror.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o jquant2.o io/LibJpeg/jquant2.c

jutils.o: io/LibJpeg/jutils.c io/LibJpeg/jinclude.h \
		io/LibJpeg/jconfig.h \
		io/LibJpeg/jpeglib.h \
		io/LibJpeg/jmorecfg.h \
		io/LibJpeg/jpegint.h \
		io/LibJpeg/jerror.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o jutils.o io/LibJpeg/jutils.c

Edge.o: imageModel/Edge.cpp imageModel/Point.h \
		imageModel/Line.h \
		imageModel/Edge.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Edge.o imageModel/Edge.cpp

Image.o: imageModel/Image.cpp imageModel/Point.h \
		imageModel/Line.h \
		imageModel/Edge.h \
		imageModel/Matrix.h \
		io/Reader.h \
		segmentation/Thresholds.h \
		segmentation/Canny.h \
		segmentation/Suzuki.h \
		imageModel/Image.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Image.o imageModel/Image.cpp

Line.o: imageModel/Line.cpp imageModel/Point.h \
		imageModel/Line.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Line.o imageModel/Line.cpp

Matrix.o: imageModel/Matrix.cpp imageModel/Point.h \
		imageModel/Matrix.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Matrix.o imageModel/Matrix.cpp

Point.o: imageModel/Point.cpp imageModel/Point.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Point.o imageModel/Point.cpp

Canny.o: segmentation/Canny.cpp imageModel/Point.h \
		imageModel/Line.h \
		imageModel/Edge.h \
		imageModel/Matrix.h \
		io/Reader.h \
		utils/Converter.h \
		segmentation/Filters.h \
		segmentation/Thresholds.h \
		segmentation/Canny.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Canny.o segmentation/Canny.cpp

Filters.o: segmentation/Filters.cpp imageModel/Point.h \
		imageModel/Matrix.h \
		segmentation/Canny.h \
		segmentation/Filters.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Filters.o segmentation/Filters.cpp

Projection.o: segmentation/Projection.cpp imageModel/Point.h \
		imageModel/Line.h \
		imageModel/Matrix.h \
		io/Reader.h \
		segmentation/Projection.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Projection.o segmentation/Projection.cpp

Suzuki.o: segmentation/Suzuki.cpp imageModel/Point.h \
		imageModel/Line.h \
		imageModel/Edge.h \
		imageModel/Matrix.h \
		io/Reader.h \
		segmentation/Thresholds.h \
		segmentation/Suzuki.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Suzuki.o segmentation/Suzuki.cpp

Thresholds.o: segmentation/Thresholds.cpp imageModel/Point.h \
		imageModel/Line.h \
		imageModel/Edge.h \
		imageModel/Matrix.h \
		segmentation/Filters.h \
		segmentation/Thresholds.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Thresholds.o segmentation/Thresholds.cpp

LBP.o: histograms/LBP.cpp imageModel/Point.h \
		imageModel/Line.h \
		imageModel/Matrix.h \
		imageModel/Image.h \
		imageModel/Edge.h \
		histograms/LBP.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o LBP.o histograms/LBP.cpp

ShapeHistogram.o: histograms/ShapeHistogram.cpp imageModel/Point.h \
		imageModel/Line.h \
		imageModel/Matrix.h \
		imageModel/Image.h \
		imageModel/Edge.h \
		histograms/ShapeHistogram.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ShapeHistogram.o histograms/ShapeHistogram.cpp

GHTInPoint.o: pht/GHTInPoint.cpp utils/Converter.h \
		imageModel/Point.h \
		imageModel/Line.h \
		imageModel/Matrix.h \
		imageModel/Image.h \
		imageModel/Edge.h \
		segmentation/Thresholds.h \
		segmentation/Canny.h \
		pht/PCA.h \
		pht/GHTInPoint.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o GHTInPoint.o pht/GHTInPoint.cpp

PCA.o: pht/PCA.cpp utils/Converter.h \
		imageModel/Point.h \
		imageModel/Line.h \
		imageModel/Matrix.h \
		imageModel/Image.h \
		imageModel/Edge.h \
		segmentation/Thresholds.h \
		segmentation/Canny.h \
		correlation/CrossCorrelation.h \
		correlation/DescriptorDistance.h \
		utils/Drawing.h \
		io/Reader.h \
		pht/GHTInPoint.h \
		pht/PCA.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o PCA.o pht/PCA.cpp

PHoughTransform.o: pht/PHoughTransform.cpp imageModel/Point.h \
		imageModel/Line.h \
		imageModel/Matrix.h \
		imageModel/Image.h \
		imageModel/Edge.h \
		pht/PHTEntry.h \
		pht/PHoughTransform.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o PHoughTransform.o pht/PHoughTransform.cpp

PHTEntry.o: pht/PHTEntry.cpp imageModel/Point.h \
		imageModel/Line.h \
		imageModel/Matrix.h \
		pht/PHTEntry.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o PHTEntry.o pht/PHTEntry.cpp

SVD.o: pht/SVD.cpp imageModel/Point.h \
		imageModel/Line.h \
		imageModel/Edge.h \
		imageModel/Matrix.h \
		imageModel/Image.h \
		pht/GHTInPoint.h \
		io/Reader.h \
		segmentation/Thresholds.h \
		pht/SVD.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SVD.o pht/SVD.cpp

GeometricHistgoram.o: pointInterest/GeometricHistgoram.cpp imageModel/Point.h \
		imageModel/Line.h \
		imageModel/Edge.h \
		imageModel/Matrix.h \
		imageModel/Image.h \
		histograms/ShapeHistogram.h \
		pointInterest/Treatments.h \
		pointInterest/GeometricHistgoram.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o GeometricHistgoram.o pointInterest/GeometricHistgoram.cpp

LandmarkDetection.o: pointInterest/LandmarkDetection.cpp imageModel/Point.h \
		imageModel/Line.h \
		imageModel/Edge.h \
		imageModel/Matrix.h \
		imageModel/Image.h \
		segmentation/Canny.h \
		segmentation/Thresholds.h \
		histograms/ShapeHistogram.h \
		pht/PHTEntry.h \
		pht/PHoughTransform.h \
		pht/GHTInPoint.h \
		correlation/CrossCorrelation.h \
		correlation/DescriptorDistance.h \
		utils/Drawing.h \
		io/Reader.h \
		pointInterest/Treatments.h \
		pointInterest/Segmentation.h \
		pointInterest/GeometricHistgoram.h \
		pointInterest/ProHoughTransform.h \
		pointInterest/LandmarkDetection.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o LandmarkDetection.o pointInterest/LandmarkDetection.cpp

ProHoughTransform.o: pointInterest/ProHoughTransform.cpp imageModel/Point.h \
		imageModel/Line.h \
		imageModel/Edge.h \
		imageModel/Matrix.h \
		imageModel/Image.h \
		segmentation/Canny.h \
		segmentation/Thresholds.h \
		pht/PHTEntry.h \
		pht/PHoughTransform.h \
		pht/GHTInPoint.h \
		io/Reader.h \
		utils/Drawing.h \
		pht/PCA.h \
		correlation/DescriptorDistance.h \
		pointInterest/Treatments.h \
		pointInterest/ProHoughTransform.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ProHoughTransform.o pointInterest/ProHoughTransform.cpp

Segmentation.o: pointInterest/Segmentation.cpp imageModel/Point.h \
		imageModel/Line.h \
		imageModel/Edge.h \
		imageModel/Matrix.h \
		imageModel/Image.h \
		segmentation/Thresholds.h \
		segmentation/Canny.h \
		segmentation/Suzuki.h \
		histograms/ShapeHistogram.h \
		io/Reader.h \
		segmentation/Filters.h \
		pointInterest/Treatments.h \
		pointInterest/Segmentation.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Segmentation.o pointInterest/Segmentation.cpp

Treatments.o: pointInterest/Treatments.cpp imageModel/Point.h \
		imageModel/Line.h \
		imageModel/Matrix.h \
		imageModel/Image.h \
		imageModel/Edge.h \
		histograms/ShapeHistogram.h \
		pointInterest/Treatments.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Treatments.o pointInterest/Treatments.cpp

CrossCorrelation.o: correlation/CrossCorrelation.cpp imageModel/Point.h \
		imageModel/Line.h \
		imageModel/Matrix.h \
		imageModel/Image.h \
		imageModel/Edge.h \
		correlation/CrossCorrelation.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CrossCorrelation.o correlation/CrossCorrelation.cpp

DescriptorDistance.o: correlation/DescriptorDistance.cpp imageModel/Point.h \
		imageModel/Line.h \
		imageModel/Matrix.h \
		segmentation/Filters.h \
		correlation/DescriptorDistance.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DescriptorDistance.o correlation/DescriptorDistance.cpp

Converter.o: utils/Converter.cpp utils/Converter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Converter.o utils/Converter.cpp

Drawing.o: utils/Drawing.cpp imageModel/Point.h \
		imageModel/Line.h \
		imageModel/Matrix.h \
		utils/Drawing.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Drawing.o utils/Drawing.cpp

ImageConvert.o: utils/ImageConvert.cpp ../../miniconda2/include/qt/QtGui/qimage.h \
		../../miniconda2/include/qt/QtGui/qcolor.h \
		../../miniconda2/include/qt/QtGui/qrgb.h \
		../../miniconda2/include/qt/QtCore/qglobal.h \
		../../miniconda2/include/qt/QtCore/qconfig.h \
		../../miniconda2/include/qt/QtCore/qfeatures.h \
		../../miniconda2/include/qt/QtCore/qsystemdetection.h \
		../../miniconda2/include/qt/QtCore/qprocessordetection.h \
		../../miniconda2/include/qt/QtCore/qcompilerdetection.h \
		../../miniconda2/include/qt/QtCore/qtypeinfo.h \
		../../miniconda2/include/qt/QtCore/qtypetraits.h \
		../../miniconda2/include/qt/QtCore/qisenum.h \
		../../miniconda2/include/qt/QtCore/qsysinfo.h \
		../../miniconda2/include/qt/QtCore/qlogging.h \
		../../miniconda2/include/qt/QtCore/qflags.h \
		../../miniconda2/include/qt/QtCore/qatomic.h \
		../../miniconda2/include/qt/QtCore/qbasicatomic.h \
		../../miniconda2/include/qt/QtCore/qatomic_bootstrap.h \
		../../miniconda2/include/qt/QtCore/qgenericatomic.h \
		../../miniconda2/include/qt/QtCore/qatomic_cxx11.h \
		../../miniconda2/include/qt/QtCore/qatomic_gcc.h \
		../../miniconda2/include/qt/QtCore/qatomic_msvc.h \
		../../miniconda2/include/qt/QtCore/qatomic_armv7.h \
		../../miniconda2/include/qt/QtCore/qatomic_armv6.h \
		../../miniconda2/include/qt/QtCore/qatomic_armv5.h \
		../../miniconda2/include/qt/QtCore/qatomic_ia64.h \
		../../miniconda2/include/qt/QtCore/qatomic_x86.h \
		../../miniconda2/include/qt/QtCore/qatomic_unix.h \
		../../miniconda2/include/qt/QtCore/qglobalstatic.h \
		../../miniconda2/include/qt/QtCore/qmutex.h \
		../../miniconda2/include/qt/QtCore/qnumeric.h \
		../../miniconda2/include/qt/QtCore/qversiontagging.h \
		../../miniconda2/include/qt/QtCore/qnamespace.h \
		../../miniconda2/include/qt/QtCore/qstringlist.h \
		../../miniconda2/include/qt/QtCore/qlist.h \
		../../miniconda2/include/qt/QtCore/qalgorithms.h \
		../../miniconda2/include/qt/QtCore/qiterator.h \
		../../miniconda2/include/qt/QtCore/qrefcount.h \
		../../miniconda2/include/qt/QtCore/qarraydata.h \
		../../miniconda2/include/qt/QtCore/qhashfunctions.h \
		../../miniconda2/include/qt/QtCore/qchar.h \
		../../miniconda2/include/qt/QtCore/qpair.h \
		../../miniconda2/include/qt/QtCore/qbytearraylist.h \
		../../miniconda2/include/qt/QtCore/qbytearray.h \
		../../miniconda2/include/qt/QtCore/qstring.h \
		../../miniconda2/include/qt/QtCore/qstringbuilder.h \
		../../miniconda2/include/qt/QtCore/qregexp.h \
		../../miniconda2/include/qt/QtCore/qstringmatcher.h \
		../../miniconda2/include/qt/QtGui/qrgba64.h \
		../../miniconda2/include/qt/QtGui/qpaintdevice.h \
		../../miniconda2/include/qt/QtGui/qwindowdefs.h \
		../../miniconda2/include/qt/QtCore/qobjectdefs.h \
		../../miniconda2/include/qt/QtCore/qobjectdefs_impl.h \
		../../miniconda2/include/qt/QtGui/qwindowdefs_win.h \
		../../miniconda2/include/qt/QtCore/qrect.h \
		../../miniconda2/include/qt/QtCore/qmargins.h \
		../../miniconda2/include/qt/QtCore/qsize.h \
		../../miniconda2/include/qt/QtCore/qpoint.h \
		../../miniconda2/include/qt/QtGui/qpixelformat.h \
		../../miniconda2/include/qt/QtGui/qtransform.h \
		../../miniconda2/include/qt/QtGui/qmatrix.h \
		../../miniconda2/include/qt/QtGui/qpolygon.h \
		../../miniconda2/include/qt/QtCore/qvector.h \
		../../miniconda2/include/qt/QtGui/qregion.h \
		../../miniconda2/include/qt/QtCore/qdatastream.h \
		../../miniconda2/include/qt/QtCore/qscopedpointer.h \
		../../miniconda2/include/qt/QtCore/qiodevice.h \
		../../miniconda2/include/qt/QtCore/qobject.h \
		../../miniconda2/include/qt/QtCore/qcoreevent.h \
		../../miniconda2/include/qt/QtCore/qmetatype.h \
		../../miniconda2/include/qt/QtCore/qvarlengtharray.h \
		../../miniconda2/include/qt/QtCore/qcontainerfwd.h \
		../../miniconda2/include/qt/QtCore/qobject_impl.h \
		../../miniconda2/include/qt/QtCore/qline.h \
		../../miniconda2/include/qt/QtGui/qpainterpath.h \
		imageModel/Point.h \
		imageModel/Matrix.h \
		utils/ImageConvert.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ImageConvert.o utils/ImageConvert.cpp

ImageViewer.o: ui/ImageViewer.cpp ../../miniconda2/include/qt/QtGui/QPainter \
		../../miniconda2/include/qt/QtGui/qpainter.h \
		../../miniconda2/include/qt/QtCore/qnamespace.h \
		../../miniconda2/include/qt/QtCore/qglobal.h \
		../../miniconda2/include/qt/QtCore/qconfig.h \
		../../miniconda2/include/qt/QtCore/qfeatures.h \
		../../miniconda2/include/qt/QtCore/qsystemdetection.h \
		../../miniconda2/include/qt/QtCore/qprocessordetection.h \
		../../miniconda2/include/qt/QtCore/qcompilerdetection.h \
		../../miniconda2/include/qt/QtCore/qtypeinfo.h \
		../../miniconda2/include/qt/QtCore/qtypetraits.h \
		../../miniconda2/include/qt/QtCore/qisenum.h \
		../../miniconda2/include/qt/QtCore/qsysinfo.h \
		../../miniconda2/include/qt/QtCore/qlogging.h \
		../../miniconda2/include/qt/QtCore/qflags.h \
		../../miniconda2/include/qt/QtCore/qatomic.h \
		../../miniconda2/include/qt/QtCore/qbasicatomic.h \
		../../miniconda2/include/qt/QtCore/qatomic_bootstrap.h \
		../../miniconda2/include/qt/QtCore/qgenericatomic.h \
		../../miniconda2/include/qt/QtCore/qatomic_cxx11.h \
		../../miniconda2/include/qt/QtCore/qatomic_gcc.h \
		../../miniconda2/include/qt/QtCore/qatomic_msvc.h \
		../../miniconda2/include/qt/QtCore/qatomic_armv7.h \
		../../miniconda2/include/qt/QtCore/qatomic_armv6.h \
		../../miniconda2/include/qt/QtCore/qatomic_armv5.h \
		../../miniconda2/include/qt/QtCore/qatomic_ia64.h \
		../../miniconda2/include/qt/QtCore/qatomic_x86.h \
		../../miniconda2/include/qt/QtCore/qatomic_unix.h \
		../../miniconda2/include/qt/QtCore/qglobalstatic.h \
		../../miniconda2/include/qt/QtCore/qmutex.h \
		../../miniconda2/include/qt/QtCore/qnumeric.h \
		../../miniconda2/include/qt/QtCore/qversiontagging.h \
		../../miniconda2/include/qt/QtCore/qrect.h \
		../../miniconda2/include/qt/QtCore/qmargins.h \
		../../miniconda2/include/qt/QtCore/qsize.h \
		../../miniconda2/include/qt/QtCore/qpoint.h \
		../../miniconda2/include/qt/QtCore/qscopedpointer.h \
		../../miniconda2/include/qt/QtGui/qpixmap.h \
		../../miniconda2/include/qt/QtGui/qpaintdevice.h \
		../../miniconda2/include/qt/QtGui/qwindowdefs.h \
		../../miniconda2/include/qt/QtCore/qobjectdefs.h \
		../../miniconda2/include/qt/QtCore/qobjectdefs_impl.h \
		../../miniconda2/include/qt/QtGui/qwindowdefs_win.h \
		../../miniconda2/include/qt/QtGui/qcolor.h \
		../../miniconda2/include/qt/QtGui/qrgb.h \
		../../miniconda2/include/qt/QtCore/qstringlist.h \
		../../miniconda2/include/qt/QtCore/qlist.h \
		../../miniconda2/include/qt/QtCore/qalgorithms.h \
		../../miniconda2/include/qt/QtCore/qiterator.h \
		../../miniconda2/include/qt/QtCore/qrefcount.h \
		../../miniconda2/include/qt/QtCore/qarraydata.h \
		../../miniconda2/include/qt/QtCore/qhashfunctions.h \
		../../miniconda2/include/qt/QtCore/qchar.h \
		../../miniconda2/include/qt/QtCore/qpair.h \
		../../miniconda2/include/qt/QtCore/qbytearraylist.h \
		../../miniconda2/include/qt/QtCore/qbytearray.h \
		../../miniconda2/include/qt/QtCore/qstring.h \
		../../miniconda2/include/qt/QtCore/qstringbuilder.h \
		../../miniconda2/include/qt/QtCore/qregexp.h \
		../../miniconda2/include/qt/QtCore/qstringmatcher.h \
		../../miniconda2/include/qt/QtGui/qrgba64.h \
		../../miniconda2/include/qt/QtCore/qsharedpointer.h \
		../../miniconda2/include/qt/QtCore/qshareddata.h \
		../../miniconda2/include/qt/QtCore/qhash.h \
		../../miniconda2/include/qt/QtCore/qsharedpointer_impl.h \
		../../miniconda2/include/qt/QtCore/qobject.h \
		../../miniconda2/include/qt/QtCore/qcoreevent.h \
		../../miniconda2/include/qt/QtCore/qmetatype.h \
		../../miniconda2/include/qt/QtCore/qvarlengtharray.h \
		../../miniconda2/include/qt/QtCore/qcontainerfwd.h \
		../../miniconda2/include/qt/QtCore/qobject_impl.h \
		../../miniconda2/include/qt/QtGui/qimage.h \
		../../miniconda2/include/qt/QtGui/qpixelformat.h \
		../../miniconda2/include/qt/QtGui/qtransform.h \
		../../miniconda2/include/qt/QtGui/qmatrix.h \
		../../miniconda2/include/qt/QtGui/qpolygon.h \
		../../miniconda2/include/qt/QtCore/qvector.h \
		../../miniconda2/include/qt/QtGui/qregion.h \
		../../miniconda2/include/qt/QtCore/qdatastream.h \
		../../miniconda2/include/qt/QtCore/qiodevice.h \
		../../miniconda2/include/qt/QtCore/qline.h \
		../../miniconda2/include/qt/QtGui/qpainterpath.h \
		../../miniconda2/include/qt/QtGui/qtextoption.h \
		../../miniconda2/include/qt/QtGui/qpen.h \
		../../miniconda2/include/qt/QtGui/qbrush.h \
		../../miniconda2/include/qt/QtGui/qfontinfo.h \
		../../miniconda2/include/qt/QtGui/qfont.h \
		../../miniconda2/include/qt/QtGui/qfontmetrics.h \
		../../miniconda2/include/qt/QtGui/QCloseEvent \
		../../miniconda2/include/qt/QtGui/qevent.h \
		../../miniconda2/include/qt/QtGui/qkeysequence.h \
		../../miniconda2/include/qt/QtCore/qvariant.h \
		../../miniconda2/include/qt/QtCore/qmap.h \
		../../miniconda2/include/qt/QtCore/qdebug.h \
		../../miniconda2/include/qt/QtCore/qtextstream.h \
		../../miniconda2/include/qt/QtCore/qlocale.h \
		../../miniconda2/include/qt/QtCore/qset.h \
		../../miniconda2/include/qt/QtCore/qcontiguouscache.h \
		../../miniconda2/include/qt/QtCore/qurl.h \
		../../miniconda2/include/qt/QtCore/qurlquery.h \
		../../miniconda2/include/qt/QtCore/qfile.h \
		../../miniconda2/include/qt/QtCore/qfiledevice.h \
		../../miniconda2/include/qt/QtGui/qvector2d.h \
		../../miniconda2/include/qt/QtGui/qtouchdevice.h \
		../../miniconda2/include/qt/QtCore/QSettings \
		../../miniconda2/include/qt/QtCore/qsettings.h \
		../../miniconda2/include/qt/QtCore/QDebug \
		../../miniconda2/include/qt/QtGui/QIcon \
		../../miniconda2/include/qt/QtGui/qicon.h \
		imageModel/Point.h \
		imageModel/Line.h \
		imageModel/Edge.h \
		imageModel/Matrix.h \
		imageModel/Image.h \
		io/Reader.h \
		segmentation/Thresholds.h \
		segmentation/Canny.h \
		segmentation/Suzuki.h \
		segmentation/Projection.h \
		segmentation/Filters.h \
		pht/GHTInPoint.h \
		pht/PHTEntry.h \
		pht/PHoughTransform.h \
		pht/PCA.h \
		pht/SVD.h \
		histograms/ShapeHistogram.h \
		histograms/LBP.h \
		pointInterest/Treatments.h \
		pointInterest/Segmentation.h \
		pointInterest/ProHoughTransform.h \
		pointInterest/LandmarkDetection.h \
		utils/ImageConvert.h \
		utils/Drawing.h \
		utils/Converter.h \
		correlation/CrossCorrelation.h \
		correlation/DescriptorDistance.h \
		MAELab.h \
		ui/ImageViewer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ImageViewer.o ui/ImageViewer.cpp

MAELab.o: MAELab.cpp imageModel/Point.h \
		imageModel/Line.h \
		imageModel/Edge.h \
		imageModel/Matrix.h \
		imageModel/Image.h \
		histograms/ShapeHistogram.h \
		pht/PHTEntry.h \
		pht/PHoughTransform.h \
		correlation/CrossCorrelation.h \
		segmentation/Thresholds.h \
		segmentation/Canny.h \
		segmentation/Suzuki.h \
		segmentation/Filters.h \
		pointInterest/Treatments.h \
		pointInterest/Segmentation.h \
		pointInterest/GeometricHistgoram.h \
		pointInterest/ProHoughTransform.h \
		pointInterest/LandmarkDetection.h \
		MAELab.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MAELab.o MAELab.cpp

MAELab_Test.o: MAELab_Test.cpp imageModel/Point.h \
		imageModel/Line.h \
		imageModel/Edge.h \
		imageModel/Matrix.h \
		imageModel/Image.h \
		utils/Drawing.h \
		io/Reader.h \
		segmentation/Thresholds.h \
		segmentation/Canny.h \
		segmentation/Filters.h \
		segmentation/Projection.h \
		correlation/DescriptorDistance.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MAELab_Test.o MAELab_Test.cpp

moc_ImageViewer.o: moc_ImageViewer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ImageViewer.o moc_ImageViewer.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

